customhost = "focswebsite.cgtpcksgf7rv.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bacs3003"
customdb = "focswebsite"
custombucket = "hohongmeng-bucket"
customregion = "us-east-1"
